--INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES (' 'videos_de_entrenamiento');

INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Entrenamiento HIIT','30 minutos','¡Acelera tu metabolismo y quema calorías con nuestro entrenamiento HIIT diseñado para desafiar y transformar tu cuerpo! El entrenamiento HIIT (High Intensity Interval Training) combina ráfagas cortas pero intensas de ejercicio con períodos de descanso activo, maximizando la quema de grasa y mejorando la resistencia cardiovascular. ',200000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/hleAwZ4mGh8?si=olbIjuNkHRVU0e0r" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Yoga para Principiantes','45 minutos','Video de yoga básico para principiantes.',90000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/FU4OTllcOXM?si=rLL2iTd17S3I-sRJ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Rutina de Fuerza','60 minutos','Video de entrenamiento de fuerza completo.',96000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/WuzTGQp-AOo?si=4XSF-pm4DfAc9STm" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Cardio Dance','40 minutos','Video de entrenamiento cardiovascular con baile.',40000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/kS0YB--Cz0U?si=LlquePl-x9qzXcw8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Pilates en Casa','50 minutos','Video de entrenamiento de pilates para casa.',70000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/oUMr3YvZBPA?si=guQH6KzDawHp_DqS" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Boxeo Cardio','35 minutos','Video de entrenamiento de boxeo con cardio.',120000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/E6eibbkPudk?si=BSZjPCS1YU6vVs1b" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Entrenamiento Funcional','55 minutos','Video de entrenamiento funcional para todo el cuerpo.',40000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/xUG92gfUmHo?si=Vzbu7O2rBC-zExG7" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Estiramientos y Movilidad','30 minutos','Video de estiramientos y mejora de la movilidad.',45000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/oC91y7SRPHU?si=2cg7pI4I1px_9uSC" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Entrenamiento de Core','25 minutos','Video de ejercicios para fortalecer el core.',57000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/c_XOTJJXfVQ?si=cI3blK7pLSCPTusV" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');
INSERT INTO servicios (nombre, duracion_video, descripcion, precio, video, categoria) VALUES ('Entrenamiento de Resistencia','45 minutos','Video de entrenamiento para mejorar la resistencia.',100000,'<iframe width="560" height="315" src="https://www.youtube.com/embed/JPjUmLNQkxI?si=Jvxl_f_l0Yqdycn_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>','videos_de_entrenamiento');

--INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES (' 'planes_nutricionales');

INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan Nutricional Básico','¡Optimiza tu salud y energía con nuestro plan nutricional básico diseñado para apoyar tu estilo de vida activo! Este plan se centra en alimentos naturales y equilibrados para proporcionarte los nutrientes necesarios sin complicaciones. ',100000,'https://nutricionvegana.org/wp-content/uploads/2017/07/plato-vegano-es-1-600.jpg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan de Pérdida de Peso','Plan de alimentación enfocado en la pérdida de peso.',260000,'https://www.ocu.org/-/media/ocu/images/home/salud/no%20center%20of%20content/landingsalud/comer_bien_800.jpg?rev=d06b340b-40bd-4867-b623-bee2d0ac2db7&mw=660&hash=859697BA97EF2285164519C8D76FAB24','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan de Ganancia Muscular','Plan de alimentación para ganar masa muscular.',290000,'https://www.mipielsana.com/wp-content/uploads/2015/04/comida-fitness.jpg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan Vegano','Plan de alimentación vegano equilibrado.',150000,'https://gritoahogado.home.blog/wp-content/uploads/2019/03/nutrinor1707.jpg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan para Deportistas','Plan de alimentación para mejorar el rendimiento deportivo.',280000,'https://www.cambiatufisico.com/wp-content/uploads/cocina-culturista-696x392.jpg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan Detox','Plan de alimentación para desintoxicación.',450000,'https://www.hola.com/imagenes/perder-peso/201701101153/plan-detox-para-despues-de-las-fiestas/0-3-654/detox-5dias--z.jpg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan Keto','Plan de alimentación cetogénico.',340000,'https://gnd-content.dev/blog/wp-content/uploads/2022/12/keto-diet.jpg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan sin Gluten','Plan de alimentación sin gluten.',240000,'https://www.acecale.org/wp-content/uploads/2018/10/celiacos-cesta-compra-kx0B-U501248042318rSF-624x385@RC.jpeg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan de Alta Energía','Plan de alimentación para aumentar la energía diaria.',270000,'https://s3.ppllstatics.com/diariovasco/www/multimedia/202001/24/media/cortadas/almendra-k8sG--624x385@Diario%20Vasco.jpg','planes_nutricionales');
INSERT INTO servicios (nombre, descripcion, precio, imagen, categoria) VALUES ('Plan de Salud Digestiva','Plan de alimentación para mejorar la salud digestiva.',340000,'https://imagenes.20minutos.es/files/image_640_360/uploads/imagenes/2023/07/06/salud-digestiva.jpeg','planes_nutricionales');
